---
title: "James_inital_eda"
author: "James"
date: "2018/10/21"
output: html_document
---


```{r}
library(dplyr)
library(ggplot2)
library(dplyr)
library(ggmap)
register_google(key = "AIzaSyAA4Odo-jCEuqZuakvUadhqg8_Z-bfXgFM")
# Note: To run this script and to use google's map service, api keys needs to be set up properly. Refer to the following link: https://stackoverflow.com/questions/36175529/getting-over-query-limit-after-one-request-with-geocode
```

```{r}
data = read.csv("data/MCI_2014_to_2017.csv", header=T, sep=",", na.strings = "NA")
data = select(data,c(-X,-Y))
data = data[!duplicated(data$event_unique_id),]
sapply(data, function(x) {sum(is.na(x))/length(x)*100})
summary(data)
```
```{r}
summary(data$offence)
```
There is are just small number of incidents reported before 2012
```{r}
summary(factor(data$occurrenceyear))
```

```{r}
ggplot(data[data$occurrenceyear>=2012,],aes(x=occurrenceyear,fill=MCI)) + geom_bar() +
  theme(axis.text.x=element_text(angle = -90, hjust = 0))
```

```{r}
lat <- data$Lat
lon <- data$Long
crimes <- data$MCI
to_map <- data.frame(crimes, lat, lon)
colnames(to_map) <- c('crimes', 'lat', 'lon')
sbbox <- make_bbox(lon = data$Long, lat = data$Lat, f = 0.1)
my_map <- get_map(location = sbbox, maptype = "roadmap", scale = 2, color="bw", zoom = 10)
ggmap(my_map) +
  geom_point(data=to_map, aes(x = lon, y = lat, color = "#27AE60"), 
             size = 0.5, alpha = 0.03) +
  xlab('Longitude') +
  ylab('Latitude') +
  ggtitle('Location of Major Crime Indicators Toronto(2014-2017 total)') +
  guides(color=FALSE)
```
```{r}
# report year vs occurence year
ggplot(data, aes(factor(occurrenceyear), fill = factor(reportedyear))) + geom_bar() +
  theme(axis.text.x=element_text(angle = -90, hjust = 0))
```
```{r}
p = ggplot(data, aes(factor(occurrencehour), factor(MCI))) + geom_bin2d() +
  scale_fill_gradient(low = "white", high = "red") +
  ylab("MCI") +
  xlab("Hours") +
  theme(legend.title = element_text(size = 10),
        legend.text = element_text(size = 12),
        plot.title = element_text(size=16),
        axis.title=element_text(size=14,face="bold"),
        axis.text.x = element_text(angle = 90, hjust = 1)) +
  labs(fill = "# of Occurance")
newdat <- ggplot_build(p)$data[[1]]
p + geom_text(data=newdat, aes((xmin + xmax)/2, (ymin + ymax)/2, label=count), col="black", angle = 90)
```

```{r}
library(maptools)
shpfile <- "/Users/james/edu/YorkU_ML/term1/assigment2/crime/NEIGHBORHOODS_WGS84_2.shp"
sh <- readShapePoly(shpfile)
sh@data$AREA_S_CD <- as.integer(sh@data$AREA_S_CD)
total_offence_cnt_table = data %>% group_by(Hood_ID) %>% summarise(offence_cnt = n())
hood_total_offence_cnt_table = merge(total_offence_cnt_table,sh@data,by.x='Hood_ID',by.y='AREA_S_CD')
points <- fortify(sh, region = 'AREA_S_CD')
points2 <- merge(points, hood_total_offence_cnt_table, by.x='id', by.y='Hood_ID', all.x=TRUE)
toronto <- qmap("Toronto, Ontario", zoom=11)
toronto + geom_polygon(aes(x=long,y=lat, group=group, fill=offence_cnt), data=points2, color='black') +
  scale_fill_gradient(low='white', high='red')

library("RColorBrewer")
toronto + geom_polygon(aes(x=long,y=lat, group=group, fill=offence_cnt), data=points2, color='black') +
  scale_fill_distiller(palette='Spectral') + scale_alpha(range=c(0.5,0.5))
```
